language: python

python:
- "3.9"

env:
- DJANGO=4.1.2

install:
- pip install -r requirements.txt
- pip install black
- pip install flake8 
- pip install coverage
- black .
- flake8 . --max-line-length=100

script:
- export DJANGO_SECRETKEY=secret
